### ISSUE TITLE
There is not enough information

### ISSUE THREAD

**Issue by Paradox75831004** [tinymins/LethalCompany-ShipGrabbableStat#1]
![image](https://github.com/tinymins/LethalCompany-ShipGrabbableStat/assets/72872478/d35457eb-d89d-4af8-a625-5bb58d1896de)
Ordinary flashlights, why does he count?

**Comment by Paradox75831004** [comment]
![image](https://github.com/tinymins/LethalCompany-ShipGrabbableStat/assets/72872478/af81f82c-3259-41a2-81f3-fc2966019f11)
Add a key count, useful information will be

**Comment by Paradox75831004** [comment]
After each scan, if the item is suddenly taken away, it should disappear from the list
![image](https://github.com/tinymins/LethalCompany-ShipGrabbableStat/assets/72872478/56dbfa43-e2f0-48e2-8a78-a3775e6fed10)

**Comment by Paradox75831004** [comment]
![image](https://github.com/tinymins/LethalCompany-ShipGrabbableStat/assets/72872478/56828314-33cf-4c5c-a7b8-3d8ade3e979e)
The mechanics of the presence of objects should be scanned inside the ship, not outside it. As in ShipLoot
The ladder should not have been counted when I took it out and scanned it on the ship again

**Comment by tinymins** [comment]
> ![image](https://private-user-images.githubusercontent.com/72872478/298868301-d35457eb-d89d-4af8-a625-5bb58d1896de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDEyOTUsIm5iZiI6MTcwNjAwMDk5NSwicGF0aCI6Ii83Mjg3MjQ3OC8yOTg4NjgzMDEtZDM1NDU3ZWItZDg5ZC00YWY4LWE2MjUtNWJiNThkMTg5NmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGNlNzJiYTRjZjAzYjZhZGM0MDZjYTAyYmM3NmM2NjMwNjVhOWU2OTVhYzI1MDJkOTU5MDU2NDZmY2I5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PePUejy6wdO3bb3Z4b6_wLVTObOrY-E32NtY3jJdTcs) Ordinary flashlights, why does he count?

Custom your own settings, see the config file.

**Comment by Paradox75831004** [comment]
> > ![image](https://private-user-images.githubusercontent.com/72872478/298868301-d35457eb-d89d-4af8-a625-5bb58d1896de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDEyOTUsIm5iZiI6MTcwNjAwMDk5NSwicGF0aCI6Ii83Mjg3MjQ3OC8yOTg4NjgzMDEtZDM1NDU3ZWItZDg5ZC00YWY4LWE2MjUtNWJiNThkMTg5NmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGNlNzJiYTRjZjAzYjZhZGM0MDZjYTAyYmM3NmM2NjMwNjVhOWU2OTVhYzI1MDJkOTU5MDU2NDZmY2I5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PePUejy6wdO3bb3Z4b6_wLVTObOrY-E32NtY3jJdTcs) Ordinary flashlights, why does he count?
> 
> Custom your own settings, see the config file.

You can add vanilla items by default

**Comment by tinymins** [comment]
> ![image](https://private-user-images.githubusercontent.com/72872478/298870599-56828314-33cf-4c5c-a7b8-3d8ade3e979e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDEyOTUsIm5iZiI6MTcwNjAwMDk5NSwicGF0aCI6Ii83Mjg3MjQ3OC8yOTg4NzA1OTktNTY4MjgzMTQtMzNjZi00YzVjLWE3YjgtM2Q4YWRlM2U5NzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MDFjMTcxNDYxNTA2OGM2NzZiZTQ2YjBmNDQ4Y2E0OWRjN2UwOTZhNWY2ZGUxYzc2NzMxYjEyZTBmNTVhYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6bFMK_g3hIFuk6G2eHKiUyPw_rqZEVgUR44DFztNx_A) The mechanics of the presence of objects should be scanned inside the ship, not outside it. As in ShipLoot The ladder should not have been counted when I took it out and scanned it on the ship again

That's the game's logic, maybe inside the fence is the "Ship", but not inside the wall. As I know, things inside the fence will not be dropped when the ship take off, it will stay as where it was.

**Comment by Paradox75831004** [comment]
I also thought about it, if the ship counted the item, then this is its territory

**Comment by tinymins** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/72872478/298868301-d35457eb-d89d-4af8-a625-5bb58d1896de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDEyOTUsIm5iZiI6MTcwNjAwMDk5NSwicGF0aCI6Ii83Mjg3MjQ3OC8yOTg4NjgzMDEtZDM1NDU3ZWItZDg5ZC00YWY4LWE2MjUtNWJiNThkMTg5NmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGNlNzJiYTRjZjAzYjZhZGM0MDZjYTAyYmM3NmM2NjMwNjVhOWU2OTVhYzI1MDJkOTU5MDU2NDZmY2I5YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PePUejy6wdO3bb3Z4b6_wLVTObOrY-E32NtY3jJdTcs) Ordinary flashlights, why does he count?
> > 
> > 
> > Custom your own settings, see the config file.
> 
> You can add vanilla items by default

Good idea, but that maybe too much? The screen may not be able to show all of that if you have every type of vanilla items.

**Comment by Paradox75831004** [comment]
Is there a problem? I just don't know... I really liked this mod - it fits into the mechanics and into our assembly "Lethal Loners"

**Comment by tinymins** [comment]
> Is there a problem? I just don't know... I really liked this mod - it fits into the mechanics and into our assembly "Lethal Loners"

After thought for a while, you're right. The default config should contains all vanilla items, if some user dont want all items show up, they should edit the config file to customize. (such as me)

**Comment by tinymins** [comment]
@Paradox75831004 btw, in your screenshots, I saw primary language is Russian. This stat plugin supports item name alias, that maybe useful for you, here's my usage screenshot:
![image](https://github.com/tinymins/LethalCompany-ShipGrabbableStat/assets/1808990/21ef94cd-0abd-46fc-87a7-c3242ca346a9)

Just edit the settings, add alias after each item name after splitter "::", here's my demo(in Chinese):

```
## Settings file was created by plugin ShipGrabbableStat v1.0.2
## Plugin GUID: com.zhaiyiming.github.tinymins.ShipGrabbableStat

[Settings]

## Grabbable names which will be stated while scan in ship, splitted by ",", use "::" to set name alias for display.
# Setting type: String
# Default value: Pro-flashlight,Shovel,Stun grenade::Stun Grenade,Spray paint::Spray Paint,TZP-Inhalant,Rocket Launcher,Jetpack,Boombox,Lockpicker,Extension ladder::Extension Ladder
StatGrabbables = Pro-flashlight::专业手电筒,Shovel::铁铲,Stun grenade::闪光弹,Spray paint::喷漆罐,TZP-Inhalant::短效兴奋剂,Rocket Launcher::火箭发射器,Jetpack::喷气背包,Boombox::音箱,Lockpicker::开锁器,Extension ladder::伸缩梯

## Hide grabbable item stat if its count is zero.
# Setting type: Boolean
# Default value: true
HideZeroItems = true

```

and here is the full vanilla items

Walkie-talkie,Flashlight,Shovel,Lockpicker,Pro-flashlight,Stun grenade::Stun Grenade,Boombox,TZP-Inhalant,Zap gun,Jetpack,Extension ladder::Extension Ladder,Radar-booster,Spray paint::Spray Paint,Rocket Launcher,Flaregun,Emergency Flare (ammo),Toy Hammer,Remote Radar,Utility Belt,Hacking Tool,Pinger,Portable Tele,Advanced Portable Tele,Night Vision Goggles,Medkit,Peeper,Helmet,Diving Kit,Wheelbarrow,Ouija Board,Shells

**Comment by Paradox75831004** [comment]
I think English is enough, we focus on the subjects in the original language
Hayrizan is responsible for the translation
I was just doing the voiceover for the game ^^
https://thunderstore.io/c/lethal-company/p/Hayrizan/RTLC_Russian_Translation/

**Comment by tinymins** [comment]
@Paradox75831004 v1.0.5 uploaded, all vanilla items are added as default items now. 

And, thanks again for your great idea ^ ^

**Comment by Paradox75831004** [comment]
It's nothing, my job is to test a lot of mods and optimize them for builds. Thank you for the wonderful mod!

**Comment by tinymins** [comment]
> ![image](https://private-user-images.githubusercontent.com/72872478/298869035-af81f82c-3259-41a2-81f3-fc2966019f11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDEyOTUsIm5iZiI6MTcwNjAwMDk5NSwicGF0aCI6Ii83Mjg3MjQ3OC8yOTg4NjkwMzUtYWY4MWY4MmMtMzI1OS00MWEyLTgxZjMtZmMyOTY2MDE5ZjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA5MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhODRhNTMxYjQyZDNkZjNhNDVjMjkzNTVmMTkxZGRkNjQxNTQzODZhZmMwNGMzYmVlYTE2YjBiOWM0YTY2MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zQRiq4V-UV2O0_7SxvizQ_ZLIDq7imVjXGlR-N7iD6Q) Add a key count, useful information will be

Key is not a buyable thing, and not in the vanilla items list. Sorry I just saw this comment, should I add "key" to default items list as well?

**Comment by tinymins** [comment]
All grabbable scraps are not included in default list not, because I dont have a name list of vanilla scraps names.

In my game experiences, ax is also a useful thing may need to be counted. Is there anything else should be counted?

**Comment by Paradox75831004** [comment]
The keys are the vanilla part of the game. You can't buy them, yes. I added them using a mod. But isn't it possible to add them, or is there a problem with that? - because it's loot

**Comment by tinymins** [comment]
> The keys are the vanilla part of the game. You can't buy them, yes. I added them using a mod. But isn't it possible to add them, or is there a problem with that? - because it's loot

Just because I don't have a full list of useful loot items which should be counted. I'll add key and ax to default list later. wait... is ax a vanilla loot item in game?

![image](https://github.com/tinymins/LethalCompany-ShipGrabbableStat/assets/1808990/b5e51566-cc2c-4e19-a760-36093b99a45d)

**Comment by Paradox75831004** [comment]
I haven't seen an axe in vanilla, it may be in development yet - but that's not for sure. For example, the mechanics of breaking through doors in the house, as from the movie "THIS IS JOHNNY!"

**Comment by Paradox75831004** [comment]
Either it's from the Scoopys_Variety_Mod by scoopy mod

**Comment by Paradox75831004** [comment]
Add some items from these mods:

MemeSoundboard v1.1.2 by Flof
HackPad v1.1.3 by willis81808

**Comment by tinymins** [comment]
I'm trying to find a full name list of vanilla store items and scraps, do you know where to find it or do you have this list? thanks!

**Comment by Paradox75831004** [comment]
I don't have this list, but I use this mod to check which items are available in general. https://thunderstore.io/c/lethal-company/p/megumin/LethalDevMode/

**Comment by tinymins** [comment]
Thanks a lot! Release 1.0.7 added Key as default item. ^ ^

**Comment by Paradox75831004** [comment]
To display the keys, I had to manually delete the config - after which everything worked and showed how it should

**Comment by tinymins** [comment]
Seems everything works great!

**Comment by Paradox75831004** [comment]
> Seems everything works great!

Yes, everything is working fine. Thanks again for the wonderful mod!
